### ISSUE TITLE
[Bug] Game crashes when enabling any ESP or nametag module with the dev builds of meteor

### ISSUE THREAD

**Issue by BookWyrm114** [cally72jhb/vector-addon#5]
upon enabling a nametag or esp module with dev build #1397, the game will crash with this error:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/10/22, 9:01 AM
Description: Unexpected error

java.lang.NoSuchFieldError: useTeamColor
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.handler$zpd000$onGetPlayerColor(PlayerUtils.java:535)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.getPlayerColor(PlayerUtils.java)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.getColor(ESP.java:306)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.getOutlineColor(ESP.java:289)
	at meteordevelopment.meteorclient.utils.render.EntityShaders.shouldDrawOutline(EntityShaders.java:67)
	at net.minecraft.client.render.WorldRenderer.handler$zoc000$renderEntity(WorldRenderer:5445)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1325)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.handler$zpd000$onGetPlayerColor(PlayerUtils.java:535)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.getPlayerColor(PlayerUtils.java)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.getColor(ESP.java:306)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.getOutlineColor(ESP.java:289)
	at meteordevelopment.meteorclient.utils.render.EntityShaders.shouldDrawOutline(EntityShaders.java:67)
	at net.minecraft.class_761.handler$zoc000$renderEntity(class_761.java:5445)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1325)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Affected level --
Details:
	All players: 26 total; [class_746['BookWyrm_'/4796482, l='ClientLevel', x=0.38, y=71.00, z=28.75], class_745['Vejkop'/4657900, l='ClientLevel', x=0.69, y=71.00, z=29.06], class_745['eduardoflame'/4796471, l='ClientLevel', x=5.23, y=69.16, z=16.19], class_745['Lupa_Lino'/4795921, l='ClientLevel', x=0.16, y=70.00, z=35.35], class_745['airplaneymation'/4795387, l='ClientLevel', x=-1.42, y=70.00, z=33.70], class_745['vqxek4vgh0'/985, l='ClientLevel', x=-5.50, y=69.00, z=17.50], class_745['5ne5ije5n5'/933, l='ClientLevel', x=-15.50, y=71.00, z=2.50], class_745['d5uuenv1jl'/935, l='ClientLevel', x=-9.50, y=71.00, z=0.50], class_745['Kheipop'/4792910, l='ClientLevel', x=0.72, y=69.00, z=0.56], class_745['8kb2ynq0wa'/931, l='ClientLevel', x=10.50, y=71.00, z=0.50], class_745['1905978x8y'/932, l='ClientLevel', x=16.50, y=71.00, z=2.50], class_745['75emxmi3q5'/934, l='ClientLevel', x=21.50, y=71.00, z=4.50], class_745['dj06hg66ot'/943, l='ClientLevel', x=-20.50, y=71.00, z=4.50], class_745['7618l56qwf'/942, l='ClientLevel', x=-25.50, y=71.00, z=-10.50], class_745['49bdzk1874'/944, l='ClientLevel', x=-20.50, y=71.00, z=-12.50], class_745['k9l5btiwma'/929, l='ClientLevel', x=-1.50, y=70.00, z=-3.50], class_745['zs7en8o511'/936, l='ClientLevel', x=-5.50, y=71.00, z=-16.50], class_745['x7uh52256i'/937, l='ClientLevel', x=-15.50, y=71.00, z=-14.50], class_745['c1ocrzaz89'/938, l='ClientLevel', x=-10.50, y=71.00, z=-15.50], class_745['8uxxzq1a01'/930, l='ClientLevel', x=2.50, y=70.00, z=-3.50], class_745['3n75x92y0t'/939, l='ClientLevel', x=6.50, y=71.00, z=-16.50], class_745['82d51crx19'/940, l='ClientLevel', x=11.50, y=71.00, z=-15.50], class_745['eotnr3e9lz'/941, l='ClientLevel', x=16.50, y=71.00, z=-14.50], class_745['q314w9ix12'/989, l='ClientLevel', x=-7.50, y=69.00, z=-27.00], class_745['fp44i8zn10'/57, l='ClientLevel', x=-29.50, y=69.00, z=3.50], class_745['kakaD47'/4794958, l='ClientLevel', x=0.50, y=69.50, z=-50.50]]
	Chunk stats: 5041, 250
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,28), Section: (at 0,7,12 in 0,4,1; chunk contains blocks 0,0,16 to 15,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 615252877 game time, 6000 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 544920504 bytes (519 MiB) / 1975517184 bytes (1884 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: spacedesk Graphics Adapter
	Graphics card #0 vendor: datronicsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.1.334.150
	Graphics card #1 name: Radeon RX 590 Series
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x67df
	Graphics card #1 versionInfo: DriverVersion=27.20.22001.14011
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40634.68
	Virtual memory used (MB): 14191.90
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 2.03
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		baritone: Baritone 1.18-SNAPSHOT
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		java: OpenJDK 64-Bit Server VM 17
		meteor-client: Meteor Client 0.4.7-1397
		minecraft: Minecraft 1.18.1
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1
		vector-addon: Vector Addon 0.2.6
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 590 Series GL version 3.2.14739 Core Profile Forward-Compatible Context 21.6.1 27.20.22001.14011, ATI Technologies Inc.
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Meteor Client (meteor-client), Fabric Loader (fabricloader)

-- Meteor Client --
Version: 0.4.7
Dev Build: 1397

[Render]:
Esp (esp)
Nametags (nametags)

[Misc]:
Discord Presence (discord-presence)

**Comment by Theboiboi8** [comment]
fixed in next release (source- #3 )

**Comment by BookWyrm114** [comment]
Thanks!
