### ISSUE TITLE
surround crashing

### ISSUE THREAD

**Issue by forota123** [cally72jhb/vector-addon#9]
---- Minecraft Crash Report ----
// Don't do that.

Time: 1/17/22, 12:15 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'int meteordevelopment.meteorclient.utils.player.FindItemResult.getSlot()'
	at cally72jhb.addon.system.modules.combat.SurroundPlus.place(SurroundPlus.java:1693)
	at cally72jhb.addon.system.modules.combat.SurroundPlus.place(SurroundPlus.java:1452)
	at cally72jhb.addon.system.modules.combat.SurroundPlus.onPreTick(SurroundPlus.java:1358)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zen000$onPreTick(class_310.java:7046)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cally72jhb.addon.system.modules.combat.SurroundPlus.place(SurroundPlus.java:1693)
	at cally72jhb.addon.system.modules.combat.SurroundPlus.place(SurroundPlus.java:1452)
	at cally72jhb.addon.system.modules.combat.SurroundPlus.onPreTick(SurroundPlus.java:1358)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zen000$onPreTick(class_310.java:7046)

-- Affected level --
Details:
	All players: 6 total; [class_746['Duhano'/1942657, l='ClientLevel', x=0.50, y=144.00, z=0.50], class_745['Duskitus69'/1884273, l='ClientLevel', x=-7.71, y=146.00, z=9.69], class_745['u3no_'/1936534, l='ClientLevel', x=18.37, y=3.18, z=2.78], class_745['Cacktine'/1938410, l='ClientLevel', x=22.30, y=4.00, z=8.30], class_745['epicgamerboi4'/1942421, l='ClientLevel', x=22.70, y=4.00, z=-1.70], class_745['BottledFish'/1936730, l='ClientLevel', x=19.70, y=3.00, z=6.70]]
	Chunk stats: 169, 169
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,144,0), Section: (at 0,0,0 in 0,9,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 89939 game time, 1000 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by cally72jhb** [comment]
That is a meteor issue a fixed version is on my discord or you wait till meteor fixes it.
